/*
  Creates a minified flashcards bank file for static hosting.

  Usage (from repo root):
    node tools/minify_flashcards_bank.js

  Output:
    interview_guide/wordpress_dev_flashcards_bank.min.js
*/

const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const inputPath = path.join(repoRoot, "interview_guide", "wordpress_dev_flashcards_bank.js");
const outputMinPath = path.join(repoRoot, "interview_guide", "wordpress_dev_flashcards_bank.min.js");

function main() {
    // Load as a classic browser global.
    global.window = {};
    require(inputPath);

    const bank = global.window.INTERVIEW_FLASHCARDS_BANK;
    if (!bank || !Array.isArray(bank.cards)) {
        console.error("Failed to load INTERVIEW_FLASHCARDS_BANK from", inputPath);
        process.exit(1);
    }

    const header = `/* Generated by tools/minify_flashcards_bank.js\n   * Source: interview_guide/wordpress_dev_flashcards_bank.js\n   */\n\n`;

    const outputMin = `${header}(function(){window.INTERVIEW_FLASHCARDS_BANK=${JSON.stringify(bank)};})();\n`;

    fs.writeFileSync(outputMinPath, outputMin, "utf8");
    console.log("Wrote:", path.relative(repoRoot, outputMinPath));
    console.log("Cards:", bank.cards.length);
}

main();
