/*
  Normalizes quiz options to reduce "correct answer is uniquely the longest" giveaways.

  Strategy:
  - Load the existing bank JS (window.WORDPRESS_DEV_BANK).
  - For any question where the correct option is strictly longer than all others,
    replace the correct option with a shorter but still-accurate summary.
  - Preserve the original full correct option by appending it to `explain`.

  Usage (from repo root):
    node tools/normalize_wordpress_dev_bank.js

  Output:
    interview_guide/wordpress_dev_bank_normalized.js
*/

const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const inputPath = path.join(repoRoot, "interview_guide", "wordpress_dev_bank.js");
const outputPath = path.join(repoRoot, "interview_guide", "wordpress_dev_bank_normalized.js");
const outputMinPath = path.join(repoRoot, "interview_guide", "wordpress_dev_bank_normalized.min.js");

function rephraseToFit(text, maxLen) {
    // Goal: keep meaning + most of the original wording, but make it not stand out in length.
    let s = String(text || "").trim();
    if (!maxLen) return s;

    // Already fits.
    if (s.length <= maxLen) return s;

    // 1) Remove common example tails first (least semantic loss).
    s = s.replace(/\s*(e\.g\.|for example)\b.*$/i, "");
    s = s.replace(/\s*\b(i\.e\.|that is)\b.*$/i, "");
    s = s.replace(/\s{2,}/g, " ").trim();
    if (s.length <= maxLen) return s;

    // 2) Remove parentheses content if still too long.
    // Do a few passes to handle nested-ish sequences.
    for (let i = 0; i < 3; i++) {
        s = s.replace(/\s*\([^)]*\)/g, "");
        s = s.replace(/\s{2,}/g, " ").trim();
        if (s.length <= maxLen) return s;
    }

    // 3) Trim at a natural boundary.
    for (const splitter of ["; ", ". ", ", "]) {
        const at = s.indexOf(splitter);
        if (at > 10) {
            const candidate = s.slice(0, at).trim();
            if (candidate.length >= 8 && candidate.length <= maxLen) return candidate;
        }
    }

    // 4) Final cap.
    if (maxLen <= 8) return s.slice(0, maxLen).trim();

    // Clip cleanly with no ellipsis (ellipsis becomes a correctness hint).
    let clipped = s.slice(0, maxLen);
    const lastSpace = clipped.lastIndexOf(" ");
    if (lastSpace > 10) clipped = clipped.slice(0, lastSpace);
    clipped = clipped.trim();
    return clipped ? clipped : "See explanation.";
}

function ensureExplain(existingExplain, originalCorrect) {
    const detail = String(originalCorrect || "").trim();
    if (!detail) return existingExplain;

    const base = existingExplain ? String(existingExplain).trim() : "";

    // Avoid duplicating if already present.
    if (base && base.includes(detail)) return base;

    const suffix = `Detail: ${detail}`;
    if (!base) return suffix;

    return `${base}\n\n${suffix}`;
}

function normalizeBank(bank) {
    const cloned = JSON.parse(JSON.stringify(bank));
    const questions = cloned.questions || [];

    let changed = 0;

    for (const q of questions) {
        if (!q || !Array.isArray(q.options) || typeof q.a !== "number") continue;

        const options = q.options.map((o) => String(o));
        const correctIndex = q.a;
        if (correctIndex < 0 || correctIndex >= options.length) continue;

        const lengths = options.map((o) => o.length);
        const correctLen = lengths[correctIndex];

        // Uniquely longest correct answer?
        const maxLen = Math.max(...lengths);
        const maxCount = lengths.filter((x) => x === maxLen).length;
        const isUniqueMax = maxCount === 1;
        if (!isUniqueMax || correctLen !== maxLen) continue;

        const maxWrong = Math.max(...lengths.filter((_, i) => i !== correctIndex));

        // If correct isn't actually longer than all wrong options, nothing to do.
        if (correctLen <= maxWrong) continue;

        const originalCorrect = options[correctIndex];
        // Rephrase to be <= the longest wrong option (so it can't remain uniquely longest).
        options[correctIndex] = rephraseToFit(originalCorrect, maxWrong);

        q.options = options;
        q.explain = ensureExplain(q.explain, originalCorrect);
        changed++;
    }

    return { normalized: cloned, changed };
}

function main() {
    // Load as a classic browser global.
    global.window = {};
    require(inputPath);

    const bank = global.window.WORDPRESS_DEV_BANK;
    if (!bank || !Array.isArray(bank.questions)) {
        console.error("Failed to load WORDPRESS_DEV_BANK from", inputPath);
        process.exit(1);
    }

    const { normalized, changed } = normalizeBank(bank);

    const header = `/* Generated by tools/normalize_wordpress_dev_bank.js
   * Source: interview_guide/wordpress_dev_bank.js
   * Purpose: reduce answer-length giveaways by shortening uniquely-longest correct options.
   */\n\n`;

    const output = `${header}(function () {\n  window.WORDPRESS_DEV_BANK = ${JSON.stringify(normalized, null, 2)};\n})();\n`;
    const outputMin = `${header}(function(){window.WORDPRESS_DEV_BANK=${JSON.stringify(normalized)};})();\n`;

    fs.writeFileSync(outputPath, output, "utf8");
    fs.writeFileSync(outputMinPath, outputMin, "utf8");
    console.log("Wrote:", path.relative(repoRoot, outputPath));
    console.log("Wrote:", path.relative(repoRoot, outputMinPath));
    console.log("Questions:", normalized.questions.length);
    console.log("Questions normalized:", changed);
}

main();
